export const initialMenuItems = [
  {
    id: 1,
    name: "Classic Cheeseburger",
    description:
      "Juicy beef patty with melted cheddar, lettuce, tomato, and pickles",
    category: "Burgers",
    price: 9.99,
    image: "",
    status: "Available",
    addOns: [
      { name: "Extra Cheese", price: 1.0 },
      { name: "Bacon", price: 1.5 },
    ],
    sizes: [
      { label: "Single", priceModifier: 0 },
      { label: "Double", priceModifier: 2 },
    ],
  },
  {
    id: 2,
    name: "Margherita Pizza",
    description:
      "Classic pizza with fresh mozzarella, tomatoes, basil, and olive oil",
    category: "Pizzas",
    price: 12.99,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [
      { label: "Small", priceModifier: 0 },
      { label: "Medium", priceModifier: 2 },
      { label: "Large", priceModifier: 4 },
    ],
  },
  {
    id: 3,
    name: "French Fries",
    description: "Crispy golden fries",
    category: "Sides",
    price: 3.99,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [],
  },
  {
    id: 4,
    name: "Cola",
    description: "Refreshing cold drink",
    category: "Drinks",
    price: 2.5,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [],
  },
  {
    id: 5,
    name: "Grilled Chicken Sandwich",
    description:
      "Grilled chicken breast with lettuce, tomato, and mayo on a toasted bun",
    category: "Sandwiches",
    price: 8.99,
    image: "",
    status: "Available",
    addOns: [
      { name: "Avocado", price: 1.5 },
      { name: "Bacon", price: 1.5 },
    ],
    sizes: [],
  },
  {
    id: 6,
    name: "Caesar Salad",
    description:
      "Crisp romaine lettuce with Caesar dressing, croutons, and parmesan",
    category: "Salads",
    price: 7.99,
    image: "",
    status: "Available",
    addOns: [
      { name: "Grilled Chicken", price: 2.0 },
      { name: "Shrimp", price: 3.0 },
    ],
    sizes: [],
  },
  {
    id: 7,
    name: "Spaghetti Bolognese",
    description:
      "Classic Italian pasta with rich meat sauce and parmesan cheese",
    category: "Pasta",
    price: 11.99,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [],
  },
  {
    id: 8,
    name: "Veggie Burger",
    description:
      "Grilled plant-based patty with lettuce, tomato, and vegan mayo",
    category: "Burgers",
    price: 9.49,
    image: "",
    status: "Available",
    addOns: [
      { name: "Vegan Cheese", price: 1.0 },
      { name: "Avocado", price: 1.5 },
    ],
    sizes: [],
  },
  {
    id: 9,
    name: "Chicken Tenders",
    description:
      "Crispy breaded chicken strips served with your choice of dipping sauce",
    category: "Appetizers",
    price: 6.99,
    image: "",
    status: "Available",
    addOns: [{ name: "Extra Sauce", price: 0.5 }],
    sizes: [],
  },
  {
    id: 10,
    name: "Chocolate Lava Cake",
    description:
      "Warm chocolate cake with a gooey molten center, served with vanilla ice cream",
    category: "Desserts",
    price: 5.99,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [],
  },
  {
    id: 11,
    name: "Buffalo Wings",
    description:
      "Spicy buffalo wings served with celery sticks and blue cheese dressing",
    category: "Appetizers",
    price: 8.99,
    image: "",
    status: "Available",
    addOns: [{ name: "Extra Sauce", price: 0.5 }],
    sizes: [],
  },
  {
    id: 12,
    name: "Pepperoni Pizza",
    description:
      "Classic pizza topped with pepperoni slices and mozzarella cheese",
    category: "Pizzas",
    price: 13.99,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [
      { label: "Small", priceModifier: 0 },
      { label: "Medium", priceModifier: 2 },
      { label: "Large", priceModifier: 4 },
    ],
  },
  {
    id: 13,
    name: "Greek Salad",
    description:
      "Fresh salad with cucumbers, tomatoes, olives, feta cheese, and vinaigrette",
    category: "Salads",
    price: 8.49,
    image: "",
    status: "Available",
    addOns: [{ name: "Grilled Chicken", price: 2.0 }],
    sizes: [],
  },
  {
    id: 14,
    name: "Fish and Chips",
    description:
      "Beer-battered fish fillets served with fries and tartar sauce",
    category: "Entrees",
    price: 12.99,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [],
  },
  {
    id: 15,
    name: "Mushroom Swiss Burger",
    description: "Beef patty topped with sautéed mushrooms and Swiss cheese",
    category: "Burgers",
    price: 10.49,
    image: "",
    status: "Available",
    addOns: [{ name: "Bacon", price: 1.5 }],
    sizes: [],
  },
  {
    id: 16,
    name: "Chicken Alfredo Pasta",
    description:
      "Fettuccine pasta tossed in creamy Alfredo sauce with grilled chicken",
    category: "Pasta",
    price: 13.49,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [],
  },
  {
    id: 17,
    name: "Garden Veggie Wrap",
    description:
      "Fresh vegetables wrapped in a whole wheat tortilla with hummus spread",
    category: "Wraps",
    price: 7.99,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [],
  },
  {
    id: 18,
    name: "BBQ Ribs",
    description: "Slow-cooked pork ribs glazed with our signature BBQ sauce",
    category: "Entrees",
    price: 15.99,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [],
  },
  {
    id: 19,
    name: "Tuna Salad Sandwich",
    description:
      "Classic tuna salad served on toasted bread with lettuce and tomato",
    category: "Sandwiches",
    price: 8.49,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [],
  },
  {
    id: 20,
    name: "Strawberry Cheesecake",
    description:
      "Creamy cheesecake topped with fresh strawberries and strawberry sauce",
    category: "Desserts",
    price: 6.49,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [],
  },
  {
    id: 21,
    name: "Iced Coffee",
    description:
      "Chilled coffee served over ice with your choice of milk and sweetener",
    category: "Drinks",
    price: 3.49,
    image: "",
    status: "Available",
    addOns: [
      { name: "Vanilla Syrup", price: 0.5 },
      { name: "Caramel Syrup", price: 0.5 },
    ],
    sizes: [
      { label: "Small", priceModifier: 0 },
      { label: "Medium", priceModifier: 0.5 },
      { label: "Large", priceModifier: 1.0 },
    ],
  },
  {
    id: 22,
    name: "Turkey Club Sandwich",
    description:
      "Sliced turkey breast, bacon, lettuce, tomato, and mayo on toasted bread",
    category: "Sandwiches",
    price: 9.99,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [],
  },
  {
    id: 23,
    name: "Lemonade",
    description: "Freshly squeezed lemonade served over ice",
    category: "Drinks",
    price: 2.99,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [
      { label: "Small", priceModifier: 0 },
      { label: "Medium", priceModifier: 0.5 },
      { label: "Large", priceModifier: 1.0 },
    ],
  },
  {
    id: 24,
    name: "Chocolate Milkshake",
    description: "Creamy chocolate milkshake topped with whipped cream",
    category: "Desserts",
    price: 4.99,
    image: "",
    status: "Available",
    addOns: [{ name: "Extra Whipped Cream", price: 0.5 }],
    sizes: [
      { label: "Small", priceModifier: 0 },
      { label: "Medium", priceModifier: 0.5 },
      { label: "Large", priceModifier: 1.0 },
    ],
  },
  {
    id: 25,
    name: "Chicken Caesar Wrap",
    description:
      "Grilled chicken, romaine lettuce, parmesan, and Caesar dressing in a wrap",
    category: "Wraps",
    price: 8.99,
    image: "",
    status: "Available",
    addOns: [],
    sizes: [],
  },
];
